### ISSUE TITLE
Add HTML, CSS and JS minification

### ISSUE THREAD

**Issue by sarg3nt** [recurser/string-is#871]
We just had a need to one time minify some HTML.  I'm not sure if this is a feature request that aligns with string-is goals or not, but if so then HTML, CSS and JavaScript minification might be good to add.

**Comment by recurser** [comment]
@sarg3nt this is a good idea 👍 https://github.com/terser/terser looks like it will do the trick for JavaScript, if it doesn't blow up the bundle size too much. I'll look into CSS and HTML as well.

Thanks for the suggestion!

**Comment by recurser** [comment]
@sarg3nt I've added a JavaScript minifier in [v1.35.0](https://github.com/recurser/string-is/releases/tag/v1.35.0)

See https://string.is/javascript-minifier

I couldn't find any good options for minifying HTML or CSS in the browser unfortunately - all of the well-maintained libraries that I could find were server-side only. 

I'll close this for now, since I think I've gotten as far as I can with it. Feel free to re-open it though if you come across any client-side libraries that look suitable though!
